---
# Install Docker
- name: Import Docker Key
  apt_key:
    state: present
    url: https://download.docker.com/linux/debian/gpg

- name: add Docker repo
  apt_repository:
    repo: https://download.docker.com/linux/debian main stable
    state: present

- name: install Docker
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: docker_packages
