---
# Install python3-apt as it might not come as standard
- name: install python3-apt
  raw: sudo apt -y install python3-apt

# apt update && upgrade
- name: Update Upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 86400

# name says it all
- name: Install Prerequisite Packages
  become: true
  package:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ prereq_packages }}"
