---
# apt update && upgrade
- name: Update Upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 86400

# name says it all
- name: Install Prerequisite Packages
  become: true
  package:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ prereq_packages }}"
